stages:
  - test

frontend_test_job:
  image: node:16.19.1
    only:
    - merge_requests
  stage: test
  before_script:
    - echo "testing pipeline"
    - echo "Installing dependencies..."
    - cd packages/gaiamundi-web && yarn install
    - echo "Deps install complete."
  script:
    - echo "Linting code..."
    - yarn lint
    - echo "No lint issues found."
    - echo "Running unit tests..."
    - yarn test:report
    - echo "Unit tests were successful!"
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml
