image: node:16.19.1

stages:          # List of stages for jobs, and their order of execution
  - test

test-job:       # This job runs in test stage
  stage: test
  script:
    - echo "Installing lerna"
    - npm i -g lerna
    - echo "Installing dependencies..."
    - yarn setup
    - echo "Deps install complete."
    - echo "Running unit tests... This will take about 60 seconds."
    - yarn test
    - echo "Unit tests were successful"
    - echo "Linting code... This will take about 10 seconds."
  #  - yarn lint
    - echo "No lint issues found."

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

