image: node:16.19.1

stages:          # List of stages for jobs, and their order of execution
  - test

test-job:       # This job runs in test stage
  stage: test
  script:
    - echo "testing pipeline"
    - echo "Installing lerna"
    - npm i -g lerna
    - echo "Installing dependencies..."
    - cd packages/gaiamundi-api && yarn install
    - cd ../..
    - cd packages/gaiamundi-web && yarn install
    - echo "Deps install complete."
    - echo "Running unit tests... This will take about 60 seconds."
    - yarn test
    - echo "Unit tests were successful"
    - echo "Linting code... This will take about 10 seconds."
    - yarn run lint
    - echo "No lint issues found."
  only:
    - merge_requests	


