workflow:
    rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge-request-event"
      when: never
    - when: always

stages:
  - test
  - deploy

frontend_test_job:
  image: node:16.19.1
  stage: test
  before_script:
    - echo "testing pipeline"
    - echo "Installing dependencies..."
    - cd packages/gaiamundi-web && yarn install
    - echo "Deps install complete."
  script:
    - echo "Linting code..."
    - yarn lint
    - echo "No lint issues found."
    - echo "Running unit tests..."
    - yarn test:report
    - echo "Unit tests were successful!"
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    when: always
    paths:
    - packages/gaiamundi-web/junit.xml
    when: always
    reports:
      junit: packages/gaiamundi-web/junit.xml

deploy_job:
  image: alpine:3.18.4
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
  script:
    echo "testing workflows..."
